// <auto-generated />
using BlazorAppEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240813025103_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UNet7BlazorAppEcomm.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A deep dive into distributed ledgers, consensus protocols, smart contracts, DApps, cryptocurrencies, Ethereum, and more 3rd ed. Edition",
                            ImageUrl = "https://m.media-amazon.com/images/I/71sZn444OfL._SL1360_.jpg",
                            Price = 9.99m,
                            Title = "Mastering Blockchain - Third Edition"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A Guide to the Cloud for SQL Server Professionals 1st ed. Edition, Kindle Edition",
                            ImageUrl = "https://m.media-amazon.com/images/I/61kXeAWGSbL._SL1180_.jpg",
                            Price = 90.99m,
                            Title = "Azure SQL Revealed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An interactive learning experience: Comprehensive introduction to data structures and algorithms (Spanish Edition) Kindle Edition",
                            ImageUrl = "https://m.media-amazon.com/images/I/81Xp21sgKIL._SL1500_.jpg",
                            Price = 19.99m,
                            Title = "Algorithms and Data Structures with Python"
                        },
                        new
                        {
                            Id = 4,
                            Description = "System design questions are often the most difficult of all technical interview questions. This book makes them easier to tackle. It is Volume 1 of the ‘System Design Interview - An Insider’s Guide’ series",
                            ImageUrl = "https://m.media-amazon.com/images/I/615KGTRs1OL._SL1500_.jpg",
                            Price = 39.99m,
                            Title = "System Design Interview"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
